/**
 * Receipt enhancement — injects REAL barcode / QR images and a digital
 * signature placeholder into receipts generated by the existing engine.
 *
 * The base generators (receipt.ts) emit `[QR Code]` / `[Barcode: …]` placeholder
 * blocks when settings.show_qr_code / show_barcode are on. This module replaces
 * those blocks with data-URL images when rendering in a browser, and appends a
 * digital-signature placeholder row on thermal receipts. When image generation
 * is unavailable (SSR / offline render), the original placeholder stays.
 */

import type { ReceiptData } from "./types";
import { generateBarcodeDataUrl, generateQrDataUrl } from "./barcode/generate";

export type ScannableGenerators = {
  barcode?: (value: string) => Promise<string | null>;
  qr?: (text: string) => Promise<string | null>;
};

const DEFAULT_GENERATORS: ScannableGenerators = {
  barcode: (value) => generateBarcodeDataUrl(value, { height: 40, width: 200, displayValue: true }),
  qr: (text) => generateQrDataUrl(text, { size: 110, margin: 1 }),
};

function escapeHtml(s: string): string {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

/** Bill verification text encoded in the QR (sale number + total). */
export function billVerificationText(data: ReceiptData): string {
  const saleNumber = data.sale?.sale_number || data.transaction_id || "N/A";
  return `SSH-BILL ${saleNumber} | ${data.hospital.name} | Total ${data.grand_total} | ${data.payment_method}`;
}

/**
 * Replace the placeholder QR block with a real QR image (if generators run).
 * Falls back to the placeholder text silently on failure.
 */
export async function enhanceReceiptWithScannables(
  html: string,
  data: ReceiptData,
  generators: ScannableGenerators = DEFAULT_GENERATORS
): Promise<string> {
  let out = html;

  if (data.settings.show_qr_code && generators.qr) {
    const url = await generators.qr(billVerificationText(data));
    if (url) {
      out = out.replace(
        /<div>\[QR Code\]<\/div>/,
        `<img src="${url}" alt="QR" style="width:34mm;height:34mm;" />`
      );
      out = out.replace(
        /<div>\[QR Code\]<\/div>\s*<div>Scan to verify bill<\/div>/,
        `<img src="${url}" alt="QR" style="width:34mm;height:34mm;" />\n<div>Scan to verify bill</div>`
      );
    }
  }

  if (data.settings.show_barcode && generators.barcode) {
    const value = data.sale?.sale_number || data.transaction_id || "";
    if (value) {
      const url = await generators.barcode(value);
      if (url) {
        out = out.replace(
          /\[Barcode: [^\]]*\]/,
          `<img src="${url}" alt="${escapeHtml(value)}" style="width:100%;max-width:60mm;height:14mm;" />`
        );
      }
    }
  }

  if (data.settings.show_return_policy === undefined || data.settings.show_return_policy) {
    // no-op — keep existing behavior
  }

  // Digital signature placeholder on thermal receipts (A4 already has one).
  if (!out.includes("Digital signature")) {
    out = out.replace(
      /<div class="center small" style="margin-top:8px;">— Computer generated bill —<\/div>/,
      `<div class="center small" style="margin-top:8px;">&nbsp;</div>
  <div class="center small">Digital signature: __SIGNATURE__</div>
  <div class="center small" style="margin-top:8px;">— Computer generated bill —</div>`
    );
  }

  return out;
}
