import {expect,test} from "@playwright/test";
test("enterprise inpatient discharge journey",async({page})=>{
 const base=process.env.PLAYWRIGHT_BASE_URL||"http://127.0.0.1:3000",email=process.env.E2E_ADMIN_EMAIL,password=process.env.E2E_ADMIN_PASSWORD;
 test.skip(!email||!password,"External staging administrator credentials required");
 await page.goto(`${base}/admin/login`);await page.locator('input[type="email"]').fill(email!);await page.locator('input[type="password"]').fill(password!);
 await Promise.all([page.waitForURL(/admin\/dashboard/),page.locator('button[type="submit"]').click()]);
 const suffix=Date.now().toString().slice(-7),phone=`903${suffix}`;
 const patientResponse=await page.request.post(`${base}/api/admin/patients`,{headers:{origin:base},data:{full_name:`Discharge E2E ${suffix}`,phone,age:61,gender:"other",address:"Staging"}});
 expect(patientResponse.status()).toBe(201);const patient=(await patientResponse.json()).data;
 const ipd=await page.request.get(`${base}/api/ipd`);expect(ipd.status()).toBe(200);const beds=(await ipd.json()).data.beds.filter((b:{status:string})=>b.status==="available");expect(beds.length).toBeGreaterThan(0);
 const admissionResponse=await page.request.post(`${base}/api/ipd`,{headers:{origin:base},data:{patient_id:patient.id,bed_id:beds[0].id,admission_type:"planned",reason:"Observation and treatment",provisional_diagnosis:"Community acquired pneumonia",care_notes:""}});
 expect(admissionResponse.status()).toBe(201);const admission=(await admissionResponse.json()).data;
 await page.goto(`${base}/admin/discharge`);
 await page.getByLabel("Discharge admission").selectOption(admission.id);
 await page.getByRole("button",{name:"Initiate discharge"}).click();await expect(page.getByText("Discharge initiated")).toBeVisible();
 const card=page.locator('[class*="rounded-2xl"]').filter({hasText:`Discharge E2E ${suffix}`}).last();
 await card.getByRole("button",{name:"Refresh clearances"}).click();await expect(page.getByText("Clearances refreshed")).toBeVisible();
 const pendingClearance=card.locator("div").filter({hasText:/inventorypending/i}).first();
 await pendingClearance.getByRole("button",{name:"Approve"}).click();await expect(page.getByText("Clearance approved")).toBeVisible();
 await card.getByLabel(/^Condition DIS-/).fill("Stable, afebrile and ambulatory");
 await card.getByLabel(/^Summary DIS-/).fill("Improved after inpatient treatment and clinically suitable for discharge.");
 await card.getByLabel(/^Medication instructions DIS-/).fill("Continue prescribed oral medicines.");
 await card.getByLabel(/^Diet instructions DIS-/).fill("Regular balanced diet and adequate fluids.");
 await card.getByLabel(/^Activity instructions DIS-/).fill("Gradual return to activity.");
 await card.getByLabel(/^Warning signs DIS-/).fill("Return for fever, breathlessness or chest pain.");
 await card.getByRole("button",{name:"Save discharge summary"}).click();await expect(page.getByText("Summary saved")).toBeVisible();
 await card.getByLabel(/^Follow-up purpose DIS-/).fill("Post-discharge clinical review");
 await card.getByLabel(/^Follow-up date DIS-/).fill(new Date(Date.now()+7*86_400_000).toISOString().slice(0,16));
 await card.getByRole("button",{name:"Add follow-up"}).click();await expect(page.getByText("Follow-up scheduled")).toBeVisible();
 await card.getByLabel(/^Referral destination DIS-/).fill("Community physician");
 await card.getByLabel(/^Referral reason DIS-/).fill("Ongoing recovery monitoring");
 await card.getByRole("button",{name:"Add referral"}).click();await expect(page.getByText("Referral added")).toBeVisible();
 await expect(card.getByRole("button",{name:"Finalize discharge"})).toBeEnabled();
 await card.getByRole("button",{name:"Finalize discharge"}).click();await expect(page.getByText("Patient discharged")).toBeVisible();
 await expect(card).toContainText("discharged");
 const report=await page.request.get(`${base}/api/discharge/report`);expect(report.status()).toBe(200);expect(await report.text()).toContain(`Discharge E2E ${suffix}`);
});
