"use client";
import {useCallback,useEffect,useState} from "react";import toast from "react-hot-toast";import {Button} from "@/components/ui/button";import {Card,CardContent} from "@/components/ui/card";import {Input} from "@/components/ui/input";import {Label} from "@/components/ui/label";import {Textarea} from "@/components/ui/textarea";
type P={id:string;full_name:string;phone:string};type F={id:string;follow_up_at:string;purpose:string;recurrence:string;status:string;reminder_status:string;hospital_patients?:{full_name:string};followup_events?:unknown[]};
export function FollowupWorkspace(){const [rows,setRows]=useState<F[]>([]),[patients,setPatients]=useState<P[]>([]),[form,setForm]=useState({patient_id:"",follow_up_at:"",department:"",purpose:"",instructions:"",recurrence:"none",reminder_at:""}),[notes,setNotes]=useState<Record<string,string>>({});
const load=useCallback(async()=>{const r=await fetch("/api/followups"),j=await r.json();if(r.ok){setRows(j.data.followups);setPatients(j.data.patients)}},[]);useEffect(()=>{void load()},[load]);
const post=async()=>{const r=await fetch("/api/followups",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,follow_up_at:new Date(form.follow_up_at).toISOString(),reminder_at:form.reminder_at?new Date(form.reminder_at).toISOString():null})}),j=await r.json();if(!r.ok)return toast.error(j.error||"Unable to schedule");toast.success("Follow-up scheduled");await load()};
const act=async(id:string,body:Record<string,unknown>)=>{const r=await fetch(`/api/followups/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)return toast.error(j.error||"Unable to update");toast.success("Follow-up updated");await load()};
return <div className="space-y-6"><div className="flex justify-between"><div><h1 className="text-2xl font-bold">Follow-up</h1><p className="text-sm text-muted-foreground">Scheduling, recurrence, reminders and clinical outcomes.</p></div><Button variant="outline" asChild><a href="/api/followups/report">Export CSV</a></Button></div><Card><CardContent className="grid gap-4 p-5 md:grid-cols-3"><Field label="Patient"><select aria-label="Follow-up patient" className="h-11 w-full rounded-xl border bg-background px-3" value={form.patient_id} onChange={e=>setForm({...form,patient_id:e.target.value})}><option value="">Select</option>{patients.map(x=><option key={x.id} value={x.id}>{x.full_name} · {x.phone}</option>)}</select></Field><Field label="Date"><Input aria-label="Follow-up date" type="datetime-local" value={form.follow_up_at} onChange={e=>setForm({...form,follow_up_at:e.target.value})}/></Field><Field label="Recurrence"><select aria-label="Follow-up recurrence" className="h-11 w-full rounded-xl border bg-background px-3" value={form.recurrence} onChange={e=>setForm({...form,recurrence:e.target.value})}>{["none","weekly","fortnightly","monthly","quarterly"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Purpose"><Input aria-label="Follow-up purpose" value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})}/></Field><Field label="Reminder"><Input aria-label="Follow-up reminder" type="datetime-local" value={form.reminder_at} onChange={e=>setForm({...form,reminder_at:e.target.value})}/></Field><Button disabled={!form.patient_id||!form.follow_up_at||!form.purpose} onClick={()=>void post()}>Schedule follow-up</Button></CardContent></Card><div className="space-y-3">{rows.map(x=><Card key={x.id}><CardContent className="space-y-3 p-5"><p className="font-bold">{x.hospital_patients?.full_name} · {new Date(x.follow_up_at).toLocaleString()}</p><p className="text-sm">{x.purpose} · {x.recurrence} · {x.status} · reminder {x.reminder_status}</p><Textarea aria-label={`Follow-up notes ${x.id}`} placeholder="Visit notes and clinical review" value={notes[x.id]||""} onChange={e=>setNotes({...notes,[x.id]:e.target.value})}/><div className="flex flex-wrap gap-2"><Button size="sm" onClick={()=>void act(x.id,{action:"status",status:"confirmed",notes:"Confirmed"})}>Confirm</Button><Button size="sm" variant="outline" onClick={()=>void act(x.id,{action:"remind"})}>Send reminder</Button><Button size="sm" onClick={()=>void act(x.id,{action:"complete",visit_notes:notes[x.id]||"Visit completed",clinical_review:notes[x.id]||"Reviewed",outcome:"Follow-up completed"})}>Complete</Button><Button size="sm" variant="outline" onClick={()=>void act(x.id,{action:"status",status:"missed",notes:"Missed"})}>Missed</Button></div><p className="text-xs text-muted-foreground">{x.followup_events?.length||0} history events</p></CardContent></Card>)}</div></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div><Label>{label}</Label>{children}</div>}

