"use client";
import {useCallback,useEffect,useState} from "react";
import toast from "react-hot-toast";
import {Button} from "@/components/ui/button";
import {Card,CardContent} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Textarea} from "@/components/ui/textarea";
type Row={id:string;referred_to:string;referral_type:string;reason:string;urgency:string;status:string;appointment_date:string|null;hospital_patients?:{full_name:string};referral_attachments?:unknown[];referral_events?:unknown[]};
type Option={id:string;full_name?:string;name?:string;phone?:string};
export function ReferralWorkspace(){
 const [rows,setRows]=useState<Row[]>([]),[patients,setPatients]=useState<Option[]>([]),[departments,setDepartments]=useState<Option[]>([]);
 const [form,setForm]=useState({patient_id:"",referral_type:"external",referred_to:"",referred_department_id:"",specialty:"",facility_name:"",reason:"",clinical_notes:"",urgency:"routine"});
 const load=useCallback(async()=>{const r=await fetch("/api/referrals"),j=await r.json();if(r.ok){setRows(j.data.referrals);setPatients(j.data.patients);setDepartments(j.data.departments)}},[]);
 useEffect(()=>{void load()},[load]);
 const create=async()=>{const payload={...form,referred_department_id:form.referred_department_id||null};const r=await fetch("/api/referrals",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),j=await r.json();if(!r.ok)return toast.error(j.error||"Unable to create referral");toast.success("Referral created");setForm({...form,patient_id:"",referred_to:"",reason:"",clinical_notes:""});await load()};
 const action=async(id:string,status:string)=>{const r=await fetch(`/api/referrals/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"status",status,notes:`Referral ${status}`})}),j=await r.json();if(!r.ok)return toast.error(j.error||"Unable to update referral");toast.success("Referral updated");await load()};
 return <div className="space-y-6"><div className="flex justify-between gap-3"><div><h1 className="text-2xl font-bold">Referrals</h1><p className="text-sm text-muted-foreground">Internal and external referral lifecycle.</p></div><Button variant="outline" asChild><a href="/api/referrals/report">Export CSV</a></Button></div>
 <Card><CardContent className="grid gap-4 p-5 md:grid-cols-3"><Field label="Patient"><select aria-label="Referral patient" className="h-11 w-full rounded-xl border bg-background px-3" value={form.patient_id} onChange={e=>setForm({...form,patient_id:e.target.value})}><option value="">Select</option>{patients.map(x=><option key={x.id} value={x.id}>{x.full_name} · {x.phone}</option>)}</select></Field><Field label="Type"><select aria-label="Referral type" className="h-11 w-full rounded-xl border bg-background px-3" value={form.referral_type} onChange={e=>setForm({...form,referral_type:e.target.value})}><option value="external">External</option><option value="internal">Internal</option></select></Field><Field label="Department"><select aria-label="Referral department" className="h-11 w-full rounded-xl border bg-background px-3" value={form.referred_department_id} onChange={e=>setForm({...form,referred_department_id:e.target.value})}><option value="">None</option>{departments.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Referred to"><Input aria-label="Referred to" value={form.referred_to} onChange={e=>setForm({...form,referred_to:e.target.value})}/></Field><Field label="Facility"><Input aria-label="Referral facility" value={form.facility_name} onChange={e=>setForm({...form,facility_name:e.target.value})}/></Field><Field label="Urgency"><select aria-label="Referral urgency" className="h-11 w-full rounded-xl border bg-background px-3" value={form.urgency} onChange={e=>setForm({...form,urgency:e.target.value})}>{["routine","urgent","emergency"].map(x=><option key={x}>{x}</option>)}</select></Field><div className="md:col-span-3"><Label>Reason</Label><Textarea aria-label="Referral reason" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></div><Button disabled={!form.patient_id||!form.referred_to||!form.reason} onClick={()=>void create()}>Create referral</Button></CardContent></Card>
 <div className="space-y-3">{rows.map(x=><Card key={x.id}><CardContent className="space-y-3 p-5"><div><p className="font-bold">{x.hospital_patients?.full_name} · {x.referred_to}</p><p className="text-sm text-muted-foreground">{x.referral_type} · {x.urgency} · {x.status}</p><p className="mt-2 text-sm">{x.reason}</p></div><div className="flex flex-wrap gap-2">{["sent","accepted","scheduled","completed","declined","cancelled"].map(s=><Button key={s} size="sm" variant={x.status===s?"default":"outline"} onClick={()=>void action(x.id,s)}>{s}</Button>)}</div><p className="text-xs text-muted-foreground">{x.referral_attachments?.length||0} attachments · {x.referral_events?.length||0} history events</p></CardContent></Card>)}</div></div>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div><Label>{label}</Label>{children}</div>}

