/**
 * Enterprise Pharmacy — Export Engine.
 * Produces CSV / JSON / Excel (.xlsx) / PDF(print) from plain row data.
 * All serializers are pure; browser download helpers are separated.
 */

export type ExportFormat = "csv" | "json" | "xlsx" | "pdf";

export type ExportColumns<T = Record<string, unknown>> = {
  key: keyof T & string;
  label: string;
}[];

/** Pick + relabel rows to a stable column order. */
export function projectRows<T extends Record<string, unknown>>(
  rows: T[],
  columns: ExportColumns<T>
): Record<string, unknown>[] {
  return rows.map((row) => {
    const out: Record<string, unknown> = {};
    for (const col of columns) {
      const v = row[col.key];
      out[col.label] = typeof v === "object" && v !== null ? JSON.stringify(v) : v;
    }
    return out;
  });
}

export function csvEscape(value: unknown): string {
  const s = value === null || value === undefined ? "" : String(value);
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

export function toCsv(rows: Record<string, unknown>[]): string {
  if (rows.length === 0) return "";
  const headers = Object.keys(rows[0]);
  const lines = [
    headers.map(csvEscape).join(","),
    ...rows.map((r) => headers.map((h) => csvEscape(r[h])).join(",")),
  ];
  return lines.join("\r\n");
}

export function toJson(rows: Record<string, unknown>[]): string {
  return JSON.stringify(rows, null, 2);
}

export function jsonToBlob(rows: Record<string, unknown>[]): Blob {
  return new Blob([toJson(rows)], { type: "application/json" });
}

export function csvToBlob(rows: Record<string, unknown>[]): Blob {
  return new Blob(["﻿" + toCsv(rows)], { type: "text/csv;charset=utf-8" });
}

/** Excel (.xlsx) via the installed SheetJS lib. */
export async function toXlsxBuffer(
  rows: Record<string, unknown>[]
): Promise<Uint8Array> {
  const XLSX = await import("xlsx");
  const ws = XLSX.utils.json_to_sheet(rows);
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, "Export");
  const buf = XLSX.write(wb, { bookType: "xlsx", type: "array" });
  return new Uint8Array(buf as ArrayBuffer);
}

export function xlsxToBlob(buf: Uint8Array): Blob {
  return new Blob([buf as unknown as BlobPart], {
    type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  });
}

/** Trigger a browser download of a Blob. */
export function downloadBlob(blob: Blob, filename: string): void {
  if (typeof window === "undefined") return;
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Render rows as a printable table (A4) and open the print dialog.
 * Used for the PDF export (browser print → Save as PDF), consistent with the
 * print engine's dependency-free PDF approach.
 */
export function buildPrintableHtml(title: string, rows: Record<string, unknown>[]): string {
  const headers = rows.length ? Object.keys(rows[0]) : [];
  const esc = (v: unknown) =>
    String(v ?? "")
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;");
  const body = rows
    .map(
      (r) =>
        `<tr>${headers.map((h) => `<td>${esc(r[h])}</td>`).join("")}</tr>`
    )
    .join("");
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>${esc(title)}</title>
<style>
  @page { size: A4; margin: 12mm; }
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #111; }
  h1 { font-size: 18px; border-bottom: 2px solid #1a5ff5; padding-bottom: 8px; }
  .meta { color:#666; font-size:12px; margin-bottom:12px; }
  table { width:100%; border-collapse: collapse; font-size: 12px; }
  th { background:#1a5ff5; color:#fff; text-align:left; padding:6px 8px; }
  td { border-bottom:1px solid #eee; padding:5px 8px; }
  tr:nth-child(even) td { background:#f8f9fa; }
  .foot { margin-top:24px; text-align:center; color:#888; font-size:11px; }
</style></head><body>
<h1>${esc(title)}</h1>
<div class="meta">${headers.length} columns · ${rows.length} rows · ${esc(
    new Date().toLocaleString()
  )}</div>
<table><thead><tr>${headers.map((h) => `<th>${esc(h)}</th>`).join("")}</tr></thead>
<tbody>${body || `<tr><td colspan="${headers.length}">No rows</td></tr>`}</tbody></table>
<div class="foot">Generated by Sri Srinivasa Hospital Pharmacy · computer generated</div>
</body></html>`;
}

export function openPrint(html: string): void {
  if (typeof window === "undefined") return;
  const w = window.open("", "_blank", "width=800,height=900");
  if (!w) return;
  w.document.write(html);
  w.document.close();
  w.focus();
  setTimeout(() => w.print(), 250);
}

export function exportRows(
  format: ExportFormat,
  rows: Record<string, unknown>[],
  filenameBase: string
): void {
  if (format === "csv") downloadBlob(csvToBlob(rows), `${filenameBase}.csv`);
  else if (format === "json") downloadBlob(jsonToBlob(rows), `${filenameBase}.json`);
  else if (format === "xlsx") {
    void toXlsxBuffer(rows).then((buf) =>
      downloadBlob(xlsxToBlob(buf), `${filenameBase}.xlsx`)
    );
  } else if (format === "pdf") {
    openPrint(buildPrintableHtml(filenameBase, rows));
  }
}
