"use client";
import {useCallback,useEffect,useState} from "react";
import toast from "react-hot-toast";
import {Button} from "@/components/ui/button";
import {Card,CardContent} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Textarea} from "@/components/ui/textarea";
type Admission={id:string;admission_number:string;status:string;provisional_diagnosis:string;hospital_patients?:{full_name:string}};
type Clearance={id:string;clearance_type:string;status:string;notes:string};
type Case={id:string;discharge_number:string;status:string;primary_diagnosis:string;condition_at_discharge:string;discharge_summary:string;hospital_patients?:{full_name:string};ipd_admissions?:{admission_number:string};discharge_clearances?:Clearance[];patient_referrals?:unknown[];patient_followups?:unknown[]};
export function DischargeWorkspace(){
 const [admissions,setAdmissions]=useState<Admission[]>([]),[cases,setCases]=useState<Case[]>([]);
 const [form,setForm]=useState({admission_id:"",primary_diagnosis:""});
 const [drafts,setDrafts]=useState<Record<string,{condition:string;summary:string;medications:string;diet:string;activity:string;warnings:string}>>({});
 const [extras,setExtras]=useState<Record<string,Record<string,string>>>({});
 const load=useCallback(async()=>{const r=await fetch("/api/discharge"),j=await r.json();if(r.ok){setAdmissions(j.data.admissions||[]);setCases(j.data.cases||[])}},[]);
 useEffect(()=>{void load()},[load]);
 const create=async()=>{const r=await fetch("/api/discharge",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,discharge_type:"routine"})}),j=await r.json();if(!r.ok)return toast.error(j.error||"Unable to initiate discharge");toast.success("Discharge initiated");setForm({admission_id:"",primary_diagnosis:""});await load()};
 const action=async(id:string,body:Record<string,unknown>,message:string)=>{const r=await fetch(`/api/discharge/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),j=await r.json();if(!r.ok)return toast.error(j.error||"Discharge update failed");toast.success(message);await load()};
 const extra=(id:string,key:string)=>extras[id]?.[key]||"";const setExtra=(id:string,key:string,value:string)=>setExtras(x=>({...x,[id]:{...x[id],[key]:value}}));
 return <div className="space-y-6"><div className="flex flex-wrap justify-between gap-3"><div><h1 className="text-2xl font-bold">Enterprise Discharge</h1><p className="text-sm text-muted-foreground">Clinical summary, cross-department clearances, referrals, follow-up and finalization.</p></div><Button variant="outline" asChild><a href="/api/discharge/report">Export discharge report</a></Button></div>
 <Card><CardContent className="grid gap-4 p-5 md:grid-cols-2"><div><Label>Active admission</Label><select aria-label="Discharge admission" className="mt-1 h-11 w-full rounded-xl border bg-background px-3" value={form.admission_id} onChange={e=>{const a=admissions.find(x=>x.id===e.target.value);setForm({admission_id:e.target.value,primary_diagnosis:a?.provisional_diagnosis||""})}}><option value="">Select admission</option>{admissions.map(a=><option key={a.id} value={a.id}>{a.admission_number} · {a.hospital_patients?.full_name}</option>)}</select></div><div><Label>Primary diagnosis</Label><Input aria-label="Discharge primary diagnosis" value={form.primary_diagnosis} onChange={e=>setForm({...form,primary_diagnosis:e.target.value})}/></div><Button disabled={!form.admission_id||!form.primary_diagnosis} onClick={()=>void create()}>Initiate discharge</Button></CardContent></Card>
 <div className="space-y-4">{cases.map(c=>{const d=drafts[c.id]||{condition:c.condition_at_discharge||"",summary:c.discharge_summary||"",medications:"",diet:"",activity:"",warnings:""};const setDraft=(key:string,value:string)=>setDrafts(x=>({...x,[c.id]:{...d,[key]:value}}));return <Card key={c.id}><CardContent className="space-y-4 p-5">
  <div className="flex flex-wrap justify-between gap-2"><div><p className="font-bold">{c.discharge_number} · {c.hospital_patients?.full_name}</p><p className="text-sm text-muted-foreground">{c.ipd_admissions?.admission_number} · {c.status} · {c.primary_diagnosis}</p></div><Button size="sm" variant="outline" onClick={()=>void action(c.id,{action:"refresh_clearances"},"Clearances refreshed")}>Refresh clearances</Button></div>
  <div className="grid gap-2 sm:grid-cols-3 lg:grid-cols-6">{(c.discharge_clearances||[]).map(x=><div key={x.id} className="rounded-xl border p-3"><p className="text-xs font-bold uppercase">{x.clearance_type}</p><p className="text-sm">{x.status}</p>{x.status!=="approved"&&<div className="mt-2 flex gap-1"><Button size="sm" onClick={()=>void action(c.id,{action:"clearance",clearance_type:x.clearance_type,status:"approved",notes:"Cleared"},"Clearance approved")}>Approve</Button><Button size="sm" variant="outline" onClick={()=>void action(c.id,{action:"clearance",clearance_type:x.clearance_type,status:"waived",notes:"Waived"},"Clearance waived")}>Waive</Button></div>}</div>)}</div>
  <div className="grid gap-3 md:grid-cols-2"><Textarea aria-label={`Condition ${c.discharge_number}`} placeholder="Condition at discharge" value={d.condition} onChange={e=>setDraft("condition",e.target.value)}/><Textarea aria-label={`Summary ${c.discharge_number}`} placeholder="Discharge summary" value={d.summary} onChange={e=>setDraft("summary",e.target.value)}/><Textarea aria-label={`Medication instructions ${c.discharge_number}`} placeholder="Medication instructions" value={d.medications} onChange={e=>setDraft("medications",e.target.value)}/><Textarea aria-label={`Diet instructions ${c.discharge_number}`} placeholder="Diet instructions" value={d.diet} onChange={e=>setDraft("diet",e.target.value)}/><Textarea aria-label={`Activity instructions ${c.discharge_number}`} placeholder="Activity instructions" value={d.activity} onChange={e=>setDraft("activity",e.target.value)}/><Textarea aria-label={`Warning signs ${c.discharge_number}`} placeholder="Warning signs and emergency advice" value={d.warnings} onChange={e=>setDraft("warnings",e.target.value)}/></div>
  <Button variant="outline" onClick={()=>void action(c.id,{action:"update_summary",secondary_diagnoses:[],procedures_performed:"",hospital_course:d.summary,condition_at_discharge:d.condition,discharge_summary:d.summary,medication_instructions:d.medications,diet_instructions:d.diet,activity_instructions:d.activity,warning_signs:d.warnings,emergency_instructions:d.warnings,transport_required:false},"Summary saved")}>Save discharge summary</Button>
  <div className="grid gap-3 rounded-xl bg-muted/40 p-3 md:grid-cols-4"><Input aria-label={`Follow-up purpose ${c.discharge_number}`} placeholder="Follow-up purpose" value={extra(c.id,"followPurpose")} onChange={e=>setExtra(c.id,"followPurpose",e.target.value)}/><Input aria-label={`Follow-up date ${c.discharge_number}`} type="datetime-local" value={extra(c.id,"followDate")} onChange={e=>setExtra(c.id,"followDate",e.target.value)}/><Button onClick={()=>void action(c.id,{action:"follow_up",follow_up_at:new Date(extra(c.id,"followDate")).toISOString(),department:"",purpose:extra(c.id,"followPurpose"),instructions:""},"Follow-up scheduled")} disabled={!extra(c.id,"followPurpose")||!extra(c.id,"followDate")}>Add follow-up</Button><p className="text-sm">{c.patient_followups?.length||0} follow-ups</p>
  <Input aria-label={`Referral destination ${c.discharge_number}`} placeholder="Referred to" value={extra(c.id,"referredTo")} onChange={e=>setExtra(c.id,"referredTo",e.target.value)}/><Input aria-label={`Referral reason ${c.discharge_number}`} placeholder="Referral reason" value={extra(c.id,"referralReason")} onChange={e=>setExtra(c.id,"referralReason",e.target.value)}/><Button onClick={()=>void action(c.id,{action:"referral",referred_to:extra(c.id,"referredTo"),specialty:"",facility_name:"",reason:extra(c.id,"referralReason"),urgency:"routine"},"Referral added")} disabled={!extra(c.id,"referredTo")||!extra(c.id,"referralReason")}>Add referral</Button><p className="text-sm">{c.patient_referrals?.length||0} referrals</p></div>
  <Button disabled={c.status!=="ready"} onClick={()=>void action(c.id,{action:"finalize"},"Patient discharged")}>Finalize discharge</Button>
 </CardContent></Card>})}</div></div>
}
