import type { PharmacySettings } from "../../src/lib/pharmacy/types";

export function fallbackSettingsForTest(): PharmacySettings {
  return {
    hospital_id: "test",
    receipt_header: "",
    receipt_footer: "Thank you!",
    receipt_paper_size: "80mm",
    show_logo: true,
    show_hospital_address: true,
    show_phone: true,
    show_gst: true,
    show_drug_license: true,
    show_doctor_name: true,
    show_patient_address: false,
    show_batch_details: true,
    show_expiry: true,
    show_mrp: true,
    show_savings: true,
    show_barcode: true,
    show_qr_code: true,
    show_return_policy: true,
    return_policy_text: "Return within 7 days.",
    default_gst_percent: 12,
    inclusive_tax: false,
    max_discount_percent: 20,
    require_discount_approval: false,
    low_stock_threshold: 10,
    expiry_alert_days: 90,
    critical_expiry_days: 30,
    enable_barcode_scanner: true,
    enable_keyboard_shortcuts: true,
    enable_sound_effects: true,
    auto_print_receipt: true,
    require_patient_for_sale: false,
    allow_credit_sales: true,
    enable_cash: true,
    enable_upi: true,
    enable_card: true,
    enable_insurance: true,
    enable_credit: true,
    enable_wallet: false,
    drug_license_number: "",
    gst_number: "",
    pharmacist_name: "",
    pharmacist_registration: "",
    standalone_mode: false,
  };
}
